version: "3"
networks: 
  expense:
volumes:
  mysql: # docker_volume create
services:
  mysql:
    image: devopsveera/mysql:v1
    container_name: mysql
    volumes:
      - mysql:var/lib/mysql
  backend:
    image: devopsveera/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: devopsveera/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on: 
      - backend