version: "3"
networks: 
  expense:
volumes:
  mysql: # docker_volume create
services:
  mysql:
    image: devopsveera/mysql:v1
    container_name: mysql
    volumes:
      - mysql:var/lib/mysql
  backend:
    image: devopsveera/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: devopsveera/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on: 
      - backend

      version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: joindevops/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: joindevops/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
    